apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/store-sandbox-namespace.yaml
  - deployments/auth/auth-deployment.yaml
  - deployments/catalog/catalog-deployment.yaml
  - deployments/product/product-deployment.yaml
  - services/catalog/catalog-service.yaml
  - services/catalog/auth-service.yaml
  - ingress/catalog/catalog-ingress.yaml
  