apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: store-sandbox
  annotations:
    buildNumber: "1.0"
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
