apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials-secret
type: Opaque
data:
  # BASE64_ENCODED_INSTANCE_ID
  GRAFANA_ID: <ID>
  # BASE64_ENCODED_TOKEN
  GRAFANA_KEY: <KEY>
  # BASE64_ENCODED_ZONE
  GRAFANA_ZONE: <ZONE>