apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  namespace: store-sandbox
  annotations:
    buildNumber: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        buildNumber: "1.0"
    spec:
      containers:
      - name: auth-service
        image: us-east1-docker.pkg.dev/hurban-lab/store/auth:latest
        readinessProbe:
          httpGet:
            path: "/auth/health/readiness"
            port: 8080
          initialDelaySeconds: 5
        ports:
        - containerPort: 8080
        env:
          - name: APPLICATION_VERSION
            value: "1.0"
          - name: SERVER_PORT
            value: "8080"
          - name: SPRING_PROFILES_ACTIVE
            value: sandbox
          - name: GRAFANA_OTLP_CLOUD_INSTANCEID
            valueFrom:
              secretKeyRef:
                name: grafana-credentials-secret
                key: GRAFANA_ID
          - name: GRAFANA_OTLP_CLOUD_APIKEY
            valueFrom:
              secretKeyRef:
                name: grafana-credentials-secret
                key: GRAFANA_KEY
          - name: GRAFANA_OTLP_CLOUD_ZONE
            valueFrom:
              secretKeyRef:
                name: grafana-credentials-secret
                key: GRAFANA_ZONE
---